config/routes.rb
Rails.application.routes.draw do
  root 'issues#index'
  get 'auth/:provider/callback', to: "sessions#create"
  delete 'sign_out', to: "sessions#destroy", as: 'sign_out'

  resources :issues do
    member do
      resources :vote, only: :create
      resources :watch, only: :create
      resources :comments, except: [:edit, :new], param: :comment_id
    end
  end

  resources :users, only: [:index]
  resources :me, only: [:index]

  get 'issues/:id/attach', to: 'issues#attach', as: :attach_to_issue
  resources :attached_files, only: :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
  enum kind: [ :bug, :enhancement, :proposal, :task ]
  enum priority: { trivial: 0, minor: 1, major: 2, critical: 3, blocker: 4 }
  enum status: { new_issue: 'New', open: 'Open', on_hold: 'On hold',
                 invalid_issue: 'Invalid', resolved: 'Resolved',
                 closed: 'Closed', wontfix: 'Wontfix', duplicate: 'Duplicate' }
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :assignee, optional: true, class_name: 'User', foreign_key: 'assignee_id'
  has_and_belongs_to_many :votes, join_table: 'table_votes', class_name: 'User'
  has_and_belongs_to_many :watchers, join_table: 'table_watchers', class_name: 'User'
  has_many :attached_files, dependent: :destroy

  # Comments
  has_many :comments
  has_many :users_commenting, through: :comments, source: :user

  validates :title, presence: true
  validates :kind, presence: true
  validates :priority, presence: true
  validate :check_assignee

  def check_assignee
    errors.add(:assignee_id, "Assignee doesn't exist") if !assignee_id.nil? && !User.exists?(id: assignee_id)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :attach]
  before_action :prepare_attachments, only: [:create, :update]
  skip_before_action :authenticate_request, only: [:index, :show]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all.order(sort_column + ' ' + sort_direction)
    @issues = @issues.where(kind: params[:kind]) if params[:kind]
    @issues = @issues.where(priority: params[:priority]) if params[:priority]
    @issues = @issues.where(status: params[:status]) if params[:status]

    if params.has_key?(:responsible)
      if User.exists?(nickname: params[:responsible])
        @issues = @issues.where(assignee_id: User
                                   .find_by(nickname: params[:responsible]).id)
      else
        @issues = []
      end
    end

    if params[:watching]
      @user = User.find_by(nickname: params[:watching])
      @issues = @issues.to_a
      if @user.nil?
        @issues.clear
      else
        @issues = @issues.select {|i| i.watchers.exists?(@user.id)}
      end
    end

    respond_to do |format|
      format.html
      format.json {render json: @issues, status: :ok, each_serializer: IndexIssueSerializer}
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @comments = @issue.comments if @issue
    respond_to do |format|
      format.html
      format.json {render json: @issue, status: :ok, serializer: ShowIssueSerializer}
    end
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # GET /issues/1/attach
  def attach
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.user = current_user
    respond_to do |format|
      if @issue.save
        if @attachments
          @attachments.each do |a|
            @issue.attached_files.create(file: a)
          end
        end

        if params[:comment] and current_user
          comment = @issue.comments.new
          comment.user = current_user
          comment.body = params[:comment]
          comment.save
        end

        format.html {redirect_to @issue, notice: 'Issue was successfully updated.'}
        format.json {render json: @issue, status: :created, serializer:
            ShowIssueSerializer}
      else
        format.html {render :new}
        format.json {render json: @issue.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        if @attachments
          @attachments.each do |a|
            @issue.attached_files.create(file: a)
          end
        end

        create_comment

        format.html {redirect_to @issue, notice: 'Issue was successfully updated.'}
        format.json {render json: @issue, status: :ok, serializer: ShowIssueSerializer}
      else
        format.html {render :edit}
        format.json {render json: @issue.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html {redirect_to issues_url, notice: 'Issue was successfully destroyed.'}
      format.json {render json: {message: 'Issue deleted successfully'}, status: :ok}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.find_by(id: params[:id])
    render json: {error: 'Issue not found'}, status: :not_found if @issue.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def issue_params
    params.permit(:title, :description, :kind, :priority, :status, :assignee_id)
  end

  def sort_column
    Issue.column_names.include?(params[:sort]) ? params[:sort] : ''
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : ''
  end

  def prepare_attachments
    @attachments = []
    if params[:attached_files]
      params[:attached_files].each do |f|
        if f.is_a?(ActionDispatch::Http::UploadedFile)
          @attachments << f
        else
          return render json: {error: 'Missing attachment parameters'}, status: :bad_request unless f[:name] && f[:content]
          @attachments << parse_attachment(f)
        end
      end
    end
  end

  def parse_attachment(attachment_data)
    attachment = Paperclip.io_adapters.for(attachment_data[:content])
    attachment.original_filename = attachment_data[:name]
    attachment
  rescue
    return render json: {error: 'Invalid attachment'}, status: :bad_request
  end

  def create_comment
    comment_body = ''

    edited_params = []
    edited_params << 'title' if params[:title]
    edited_params << 'description' if params[:description]
    edited_params << 'kind' if params[:kind]
    edited_params << 'status' if params[:status]
    edited_params << 'priority' if params[:priority]

    added_attachments = []
    if @attachments
      @attachments.each do |f|
        added_attachments << f.original_filename
      end
    end

    new_assignee = nil
    unless params[:assignee_id].nil? || !User.exists?(params[:assignee_id])
      new_assignee = User.find_by(id: params[:assignee_id]).name
    end

    unless edited_params.empty?
      comment_body += '<p><ul><li>'
      comment_body += "<strong>#{current_user.name}</strong>"
      comment_body += ' has modified the issue attribute'
      comment_body += 's' if edited_params.size > 1
      comment_body += ' <i>' + edited_params.to_sentence + '</i>'
      comment_body += '.</li>'
    end

    unless added_attachments.empty?
      if edited_params.empty?
        comment_body += '<p><ul><li>'
        comment_body += "<strong>#{current_user.name}</strong>"
      elsif new_assignee.nil?
        comment_body += ' and'
      else
        comment_body += ','
      end
      comment_body += ' has attached the file'
      comment_body += 's' if added_attachments.size > 1
      comment_body += ' <i>' + added_attachments.to_sentence + '</i>'
      comment_body += '.</li>'
    end


    if params.has_key?(:assignee_id)
      if edited_params.empty? and added_attachments.empty?
        comment_body += '<p><ul><li>'
        comment_body += "<strong>#{current_user.name}</strong>"
      else
        comment_body += ' and'
      end

      if User.find_by(id: params[:assignee_id]).nil?
        comment_body += ' has removed the assignee'
      else
        comment_body += ' has assigned this issue to <strong>' + new_assignee + '</strong>'
      end
      comment_body += '.</li>'
    end

    unless comment_body.empty?
      comment_body += '</ul></p>'
    end

    if params[:comment]
      comment_body += params[:comment]
    end

    unless comment_body.empty?
      comment = Comment.new
      comment.body = comment_body
      comment.issue = @issue
      comment.user = current_user
      comment.save
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for @issue, html: { multipart: true } do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation" class="errors">
      <p><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</p>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-group">
    <%= f.label :title %>
    <%= f.text_field :title, name: 'title' %>
  </div>

  <div class="field-group">
    <%= f.label :description %>
    <%= f.text_area :description, name: 'description' %>
  </div>

  <div class="field-group">
    <%= f.label :assignee %>
    <%= f.select :assignee_id, User.all.collect {|mt| [ mt.name, mt.id ] }, {:include_blank => ''}, name: 'assignee_id' %>
  </div>

  <div class="field-group">
    <%= f.label :kind %>
    <%= f.select :kind, [['bug'], ['enhancement'], ['proposal'], ['task']], {}, name: 'kind' %>
  </div>

  <div class="field-group">
    <%= f.label :priority %>
    <%= f.select :priority, [['trivial'], ['minor'], ['major'], ['critical'], ['blocker']], {}, name: 'priority' %>
  </div>
  
  <div class="field-group">
    <%= f.label :status %>
    <%= f.select :status, [['New', 'new_issue'],
                           ['Open', 'open'],
                           ['On hold', 'on_hold'],
                           ['Invalid', 'invalid_issue'],
                           ['Resolved', 'resolved'],
                           ['Closed', 'closed']], {}, name: 'status' %>
  </div>

    <div class="field-group">
      <%= f.label :attachments %>
      <ul id="existing-attached-files-list" class="attached-files-list">
        <% @issue.attached_files.each do |attachment| %>
            <li><a href="<%= attachment.file.url %>"><%= attachment.file_file_name %></a></li>
        <% end %>
      </ul>
      <ul id="attached-files-list" class="attached-files-list newfiles"></ul>
      </ul>
      <div class="myFile">
        <button class="aui-button">Select files</button>
        <%= file_field_tag 'attached_files[]', id: 'attachment-upload', class:'assistive', onchange: 'javascript:updateUploads()', multiple: true %>
      </div>
    </div>

    <div class="actions">
    <%= f.submit 'Create issue', :class => 'submit' %>
    <%= link_to 'Cancel', issues_path, :class => 'cancel' %>
  </div>
<% end %>

app/views/issues/_form_attach.html.erb
<%= form_for @issue, html: { multipart: true } do |f| %>

    <div class="field-group">
      <%= f.label :attachments %>
      <ul id="existing-attached-files-list" class="attached-files-list">
        <% @issue.attached_files.each do |attachment| %>
            <li><a href="<%= attachment.file.url %>"><%= attachment.file_file_name %></a></li>
        <% end %>
      </ul>
      <ul id="attached-files-list" class="attached-files-list newfiles"></ul>
      <div class="myFile">
        <button class="aui-button">Select files</button>
        <%= file_field_tag 'attached_files[]', type: :file, id: 'attachment-upload', class:'assistive', onchange: 'javascript:updateUploads()', multiple: true %>
      </div>
    </div>

  <div class="actions">
    <%= f.submit 'Upload files', :class => 'submit' %>
    <%= link_to 'Cancel', issues_path, :class => 'cancel' %>
  </div>
<% end %>

app/views/issues/attach.html.erb
<div class="header">
  <div class="section-title">
    <h1>Issues</h1>
  </div>
  <div class="page-actions"></div>
</div>

<div class="issue-main-view">
  <div class="issue-header">
    <span class="issue-id">
      Issue #<%= @issue.id %>
    </span>
  </div>
  <h2>Attach files</h2>

  <%= render 'form_attach', issue: @issue %>

  <%= link_to 'Back', issues_path, :class => 'back' %>
</div>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <div class="section-title">
    <h1>Issues</h1>
  </div>
  <div class="page-actions">
    <% if current_user %>
      <%= link_to new_issue_path, class: 'aui-button aui-button-subtle' do %>
        <span class="add-icon">+</span>
        <span class="aui-button-label">Create issue</span>
      <% end %>
    <% end %>
  </div>
</div>


<div class="issues">

  <div class="issues-toolbar">
    <div class="filter-container">
      <p class="filter-label">Filters:</p>
      <ul class="filter-status">
        <li id="all" class="aui-button">
          <a href="/issues">All</a>
        </li>
        <li id="open" class="aui-button">
          <a href="/issues?status=open">Open</a>
        </li>
        <% if current_user %>
          <li id="mine" class="aui-button">
            <a href="/issues?responsible=<%= current_user.nickname %>">My issues</a>
          </li>
          <li id="watching" class="aui-button">
            <a href="/issues?watching=<%= current_user.nickname %>">Watching</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <h2>Issues (<%= @issues.to_a.size %>)</h2>

  <p id="issues-filter-criteria">
    <% if request.query_parameters[:kind] %>
      <b>type:</b> "<%= request.query_parameters[:kind] %>"
    <% end %>
    <% if request.query_parameters[:priority] %>
        <b>priority:</b> "<%= request.query_parameters[:priority] %>"
    <% end %>
    <% if request.query_parameters[:status] %>
        <b>status:</b> "<%= Issue.statuses[request.query_parameters[:status]] %>"
    <% end %>
    <% if request.query_parameters[:responsible] %>
        <b>assignee:</b> "<%= request.query_parameters[:responsible] %>"
    <% end %>
  </p>

  <table class="issue-list">
    <thead>
    <%= sortable "id", "Title" %>
    <%= sortable "kind", "T" %>
    <%= sortable "priority", "P" %>
    <%= sortable "status", "S" %>
    <%= sortable "votes", "Votes" %>
    <%= sortable "assignee_id", "Assignee" %>
    <%= sortable "created_at", "Created" %>
    <%= sortable "updated_at", "Updated" %>
    </thead>
    <tbody>
      <% @issues.each do |issue| %>
        <tr>
          <td class="text">
            <%= link_to '#' << issue.id.to_s << ': ' << issue.title, issue %>
          </td>
          <td class="text">
            <a href="/issues?kind=<%= issue.kind %>"
               class="icon-kind icon-<%= issue.kind %>"
               title="Filter by type: <%= issue.kind %>">
              <%= issue.kind %></a>
          </td>
          <td class="text">
            <a href="/issues?priority=<%= issue.priority %>"
               class="icon-priority icon-<%= issue.priority %>"
               title="Filter by priority: <%= issue.priority %>">
              <%= issue.priority %>
            </a>
          </td>
          <td class="text">
            <a href="/issues?status=<%= issue.status %>"
               class="icon-status icon-<%= issue.status %>"
               title="Filter by status: <%= Issue.statuses[issue.status] %>">
              <%= Issue.statuses[issue.status] %>
            </a>
          </td>
          <td class="text">
            <% if issue.votes.size > 0 %>
              <span class="aui-badge issue-count-<%= issue.votes
                                .include?(current_user) ? 'no' : 'yes' %>">
                <%= issue.votes.size %>
              </span>
            <% end %>
          </td>
          <td class="text">
            <% if issue.assignee_id %>
                <a href="/issues?responsible=<%= issue.assignee.nickname %>">
                  <img class="assignee-icon" src=<%= issue.assignee.image_url %>
                      <span title="author-name"><%= issue.assignee.name %></span>
                </a>
            <% end %>
          </td>
          <td class="date">
            <%= issue.created_at.to_date %>
          </td>
          <td class="date">
            <%= issue.updated_at.to_date %>
          </td>
        </tr>
      <% end %>
  </table>
</div>

app/views/issues/new.html.erb
<h1 class="title">Create issue</h1>

<%= render 'form', issue: @issue, users: @users %>

<%= link_to 'Back', issues_path, :class => 'back' %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <div class="section-title">
    <h1>Issues</h1>
  </div>
  <div class="page-actions"></div>
</div>

<div class="issue-main-view">
  <div class="issue-header">
    <span class="issue-id">
      Issue #<%= @issue.id %>
    </span>
    <div class="issue-toolbar">
      <% if current_user %>
          <a href="/issues/<%= @issue.id %>/attach" class="aui-button">Attach</a>

            <a href="/issues/<%= @issue.id %>/edit" class="aui-button">Edit</a>
            <%= link_to 'Delete', @issue,  method: :delete, class: 'aui-button', data: { confirm: 'Are you sure you want to delete this issue?' } %>

      <% end %>
    </div>
  </div>

  <div class="issue-main-content">
    <div class="issue-info">

      <div class="issues-toolbar">
      </div>

      <h1 id="issue-title"><%= @issue.title %></h1>

      <div class="issue-author">
        <a href="/issues?responsible=<%= @issue.user.nickname %>">
          <div class="aui-avatar aui-avatar-medium">
            <div class="aui-avatar-inner">
              <img src=<%= @issue.user.image_url %>>
            </div>
          </div>
          <span title="author-name"><%= @issue.user.name %></span>
        </a>
        created an issue
        <time class="created_at"><%= @issue.created_at.strftime('%Y-%m-%d')
        %></time>
      </div>

      <div class="issue-description">
        <% if @issue.description %>
            <p class="description"><%= @issue.description %></p>
        <% else %>
            <p class="no-description">No description provided.</p>
        <% end %>
      </div>

      <div class="attachments">
        <ul class="issue-attachment-list attachment-list clearfix">
          <% @issue.attached_files.each do |attached_file| %>
              <li>
                <a class="attachment-link" target="_blank" href="<%= attached_file.file.url %>">
                  <span class="placeholder default"></span>
                  <span class="filename"><%= attached_file.file_file_name %></span>
                </a>
                <%= link_to attached_file,  method: :delete, class: 'delete-attachment', data: { confirm: 'Are you sure you want to delete this attachment?' } do %>
                    <img class="delete-icon" src="<%= image_url('delete_black.png') %>">
                <% end %>

              </li>
          <% end %>
        </ul>
      </div>

      <div class="issue-comments-container"></div>
    </div>

    <div class="sidebar">
      <div class="issue-attrs">
        <dl>
          <dt>Type</dt>
          <dd class="type with-icon">
            <a href="/issues?kind=<%= @issue.kind %>">
              <span class="icon-kind icon-<%= @issue.kind %>"></span>
              <%= @issue.kind %>
            </a>
          </dd>
        </dl>
        <dl>
          <dt>Priority</dt>
          <dd class="priority with-icon">
            <a href="/issues?priority=<%= @issue.priority %>">
              <span class="icon-priority icon-<%= @issue.priority %>"></span>
              <%= @issue.priority %>
            </a>
          </dd>
        </dl>
        <dl>
          <dt>Status</dt>
          <dd class="status with-icon">
            <a href="/issues?status=<%= @issue.status %>">
              <span class="icon-status icon-<%= @issue.status %>"></span>
              <%= Issue.statuses[@issue.status] %>
            </a>
          </dd>
        </dl>
        <% if @issue.assignee %>
        <dl>
          <dt>Assigned to</dt>
          <dd>
            <a href="/issues?responsible=<%= @issue.assignee.nickname %>">
                <img class="assignee-icon" src=<%= @issue.assignee.image_url %>
              <span title="author-name"><%= @issue.assignee.name %></span>
            </a>
          </dd>
        </dl>
        <% end %>
        <dl>
          <dt>Votes</dt>
          <dd class="votes">
            <span class="aui-badge issue-count-<%= @issue.votes
                                                       .include?(current_user) ? 'no' : 'yes' %>">
              <%= @issue.votes.size %>
            </span>
            <% if current_user %>
                <a href="/issues/<%= @issue.id %>/vote" data-method="create">
                  <%= (@issue.votes.exists?(current_user.id)) ? 'Remove vote' :
                          'Vote for this issue' %>
                </a>
            <% end %>
          </dd>
        </dl>
        <dl>
          <dt>Watchers</dt>
          <dd class="watchers">
            <span class="aui-badge issue-count-<%= @issue.watchers
                                                       .include?(current_user) ? 'no' : 'yes' %>">
              <%= @issue.watchers.size %>
            </span>
            <% if current_user %>
                <a href="/issues/<%= @issue.id %>/watch" data-method="create">
                  <%= (@issue.watchers.exists?(current_user.id)) ? 'Stop watching' :
                          'Watch this issue' %>
                </a>
            <% end %>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>